FROM agrigorev/zoomcamp-model:2025

WORKDIR /app

COPY "pyproject.toml" "uv.lock" ".python-version" "./"

RUN uv sync --locked

COPY "predict.py" "test_client.py" "conversion.py" "pipeline_v1.bin" "./"

EXPOSE 9696

ENTRYPOINT ["uvicorn", "predict:app", "--host", "0.0.0.0", "--port", "9696"]